Configuration:
  Name: foxtrot

Subsystem:
  mrcyNtrip:
    Type: Sensor
    Description: command to start mrcyNtrip
    HealthTopics:
    Commands:
      - Name: mrcyNtrip
        Command: mrcyNtrip
        Type: Software
        LaunchTime: 5
    Depends: 
  CAN:
    Type: Sensor
    Description: Vehicle CAN
    HealthTopics:
      - HealthTopic: /CtrlStateFLG
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: CanZe1SvConsumer
        Command: roslaunch nrc_leaf can_communication_modular.launch numChannels:=4 CanZe1SvConsumer:=true CanZe1SvWriter:=true Eyeq3Prod:=true Eyeq3ProdCh:=1 Eyeq4Dev:=true Eyeq4DevCh:=2 Eyeq4DevWrite:=true Eyeq4DevWriteCh:=2 Eyeq4DevFS:=true Eyeq4DevFSCh:=3
        Type: Software
        LaunchTime: 5.0
    Diagnostic:
      LED: 1
      Retry: 5
      Timeout: 30
      File:
    Depends:
    
  ARD:
    Type: Sensor
    Description: Leaf Arduino
    HealthTopics:
      # - HealthTopic: /driver_marker_button
      #   HealthName: ARD
      #   HealthTopicType: Int16
      #   NomWarnErrRate: 10, 8, 1
    Commands:
      - Name: ARD
        Command: roslaunch nrc_hw_svcs leaf_interface_arduino.launch arduino_machine:=node02
        Type: Software
        LaunchTime: 1.0
    Diagnostic:
      LED:
      Retry: 0
      Timeout: 30
    Depends:

  GPS_Raw:
    Type: Sensor
    Description: Raw GPS
    HealthTopics:
      - HealthTopic: /gps_state/dynamic_global_pose_oxts
        HealthName: OxtsRaw
        HealthTopicType: DynamicPoseWithCovar
        NomWarnErrRate: 100, 80, 60
    Commands:
      - Name: GPS_Raw
        Command: roslaunch nrc_hw_svcs gps_leaf.launch
        Type: Software
        LaunchTime: 5.0
      - Name: TF_Sys
        Command: roslaunch nrc_svcs leaf_tf_subsystem.launch sanborn:=true
        Type: Software
        LaunchTime: 1.0
    Diagnostic: 
      File: gps_raw_diag.py
      LED:
      Retry: 5
      Timeout: 30
    Depends:

  Pose:
    Type: Algorithm
    Description: Vehicle Pose
    HealthTopics:
      - HealthTopic: /dynamic_global_pose
        HealthName: DGP
        HealthTopicType: DynamicPoseWithCovar
        NomWarnErrRate: 100, 80, 60
    Commands:
      - Name: GPS_Matched
        Command: rosrun nrc_wm2_svcs map_match name:=MapMatch_node _useOxts:=true
        Type: Software
        LaunchTime: 3.0
    Diagnostic: 
      File: pose_diag.py
      LED: 2
      Retry: 5
      Timeout: 30
    Depends: GPS_Raw

  Eyeq5:
    Type: Sensor
    Description: Mobileye Camera
    HealthTopics:
      - HealthTopic: /ME5/health
        HealthName: NOD
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /ME5_ObjData
        HealthName: ME5
        HealthTopicType: Mobileye5ObjectArray
        NomWarnErrRate: 30, 20, 10
    Commands:
      - Name: Can_Com_Eyeq5
        Command: roslaunch nrc_leaf can_communication_modular.launch numChannels:=2 Eyeq5DevCh0:=true Eyeq5DevCh0Ch:=0 Eyeq5DevWrite:=true Eyeq5DevWriteCh:=0 Eyeq5DevCh1:=true Eyeq5DevCh1Ch:=1 nodeName:=eyeq5CanCom machine:=node03
        Type: Software
        LaunchTime: 2.0
    Diagnostic: 
      File: eyeq5_diag.py
      LED: 3
      Retry: 5
      Timeout: 30
    Depends:

  Velodyne:
    Type: Sensor
    Description: Velodyne
    HealthTopics:
      - HealthTopic: /velodyne_health
        HealthName: VLDY
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: VelodyneDriver
        Command: roslaunch velodyne_pointcloud VLS128_points.launch velodyne_machine:=local
        Type: Software
        LaunchTime: 1.0
    Diagnostic: 
      File: velo_diag.py
      LED:
      Retry: 5
      Timeout: 30
    Depends:

  PCP:
    Type: Algorithm
    Description: Pointcloud_Processing
    HealthTopics:
      - HealthTopic: /pc_processor/multi_object_tracker/tracked_object_set
        HealthName: PCP_TOS
        HealthTopicType: TrackedObjectSet
        NomWarnErrRate: 10, 7, 3
      - HealthTopic: /drivable_area_boundary_points
        HealthName: PCP_DA
        HealthTopicType: PointCloud2
        NomWarnErrRate: 10, 7, 3
    Commands:
      - Name: PCP
        Command: roslaunch nrc_pcp_svcs pc_processor.launch dynamic_global_pose_topic_name:=/dynamic_global_pose do_road_surf_change_detection:=true Leaf_Foxtrot:=true
        Type: Software
        LaunchTime: 3.0
      - Name: Me2Yolo
        Command: roslaunch nrc_perc_svcs mobileye_yolo_converters.launch
        Type: Software
        LaunchTime: 1.0
    Diagnostic:
      LED: 4
      Retry: 2
      Timeout: 30
      File: pcp_diag.py
    Depends:
    
    
  CAM:
    Type: Algorithm
    Description: Tower_Cams
    HealthTopics:
      - HealthTopic: /tower_cam_front/image_stamped
        HealthName: TCF
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 7, 3
    Commands:
      - Name: CAM
        Command: roslaunch nrc_hw_svcs pgr_gige_cameras.launch FrRCam:=true FrLCam:=true FrCam:=true BaRCam:=false BaLCam:=false BaCam:=false enableArduino:=true video_preprocess:=true leaf_foxtrot:=true
        Type: Software
        LaunchTime: 5.0
    Diagnostic: 
      LED: 
      Retry: 5
      Timeout: 5
    Depends:

  WM:
    Type: Algorithm
    Description: World Model
    HealthTopics:
      - HealthTopic: /object_tracker/health
        HealthName: Fusion
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /traffic_light/detection/health
        HealthName: TLR
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 1, 0.6, 0.3
      - HealthTopic: /ailsv_virtual_objects
        HealthName: Virtual
        HealthTopicType: TrackedObjectSet
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /master_filter/health
        HealthName: WOS
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: WM
        Command: roslaunch nrc_wm2_svcs leaf_pred.launch
        Type: Software
        LaunchTime: 1.0
    Diagnostic:
      LED: 5
      Retry: 3
      Timeout: 30
      File: 
    Depends:
     

  AutoGoals:
    Type: Algorithm
    Description: AutoGoals
    HealthTopics:
      - HealthTopic: /drive_plan
        HealthName: DRV_PLAN
        HealthTopicType: DriveGoalList
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: AutoGoals
        Command: roslaunch nrc_wm2_svcs leaf_route.launch
        Type: Software
        LaunchTime: 3.0
    
    Depends:
    Diagnostic:
      LED: 6
      Retry: 5
      Timeout: 30
    # Diagnostic:

  Trajectory:
    Type: Algorithm
    Description: Trajectory Planner/Follower
    HealthTopics:
      - HealthTopic: /lane_planner_state
        HealthName: TrajP
        HealthTopicType: LanePlannerState
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /lane_follower_state
        HealthName: TrajC
        HealthTopicType: TrajectoryControllerState
        NomWarnErrRate: 100, 60, 10
    Commands:
      - Name: Trajectory Planner
        Command: roslaunch nrc_ralp_svcs leaf_planner.launch use_predictor:=true publish_force_control:=true vehicle_type:=LeafFS
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      LED: 7
      Retry: 5
      Timeout: 30
    Depends: