Configuration:
  Name: fvla-infrapod
  Map: Franklin.set
  useGui: 0
  sendWm: 1
  broker: doris

Subsystem:
  LIDAR:
    Type: Sensor
    Description: command to start innovusion node
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: Startup
    HealthTopics:
      - HealthTopic: /iv_points
        HealthName: IV
        HealthTopicType: PointCloud2
        NomWarnErrRate: 10, 7, 1
    Commands:
      - Name: Innovusion
        Command: bash $HOME/projects/fvla-infrapod/nrc_ws/src/nrc_svcs/scripts/runInnovusionInfraPod.sh > /dev/null
        NodeName: innovusion_nodelet_manager
        Type: Software
        LaunchTime: 1
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:
  
  PCP:
    Type: Algorithm
    Description: command to start point cloud processor
    Trigger:
      - Source: Startup
    HealthTopics:
      - HealthTopic: /drivable_area_boundary_points
        HealthName: DA
        HealthTopicType: PointCloud2
        NomWarnErrRate: 10, 7, 1
      - HealthTopic: /pc_processor/multi_object_tracker/tracked_object_set
        HealthName: TOS
        HealthTopicType: TrackedObjectSet
        NomWarnErrRate: 10, 7, 1
    Commands:
      - Name: PCP
	Command: roslaunch nrc_pcp_svcs pc_processor.launch Leaf_Foxtrot:=false Infra_Tripod:=true
        NodeName: pc_processor_ros_node
        Type: Algorithm
        LaunchTime: 1
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch: Innovusion
        Run:    
  
  Bridge:
    Type: Software
    Description: convert ros messages to mqtt
    Trigger:
      - Source: Startup
    Commands:
      - Name: MQTT
        Command: rosrun ros_mqtt_parser ros_mqtt_node _config_file:=$(rospack find ros_mqtt_parser)/config/config.yaml
        Type: Algorithm
        LaunchTime: 3.0
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:

  TOSTF:
    Type: Algorithm
    Description: Transform TOS to map frame
    Trigger:
      - Source: Startup
    Commands:
      - Name: TrackedObjectSetMap
        Command: python ${HOME}/projects/fvla-infrapod/calibration_scripts/FY_24_calib_scripts/infrapod_code/publish_TOS_map.py 1
        Type: Algorithm
        LaunchTime: 3.0
    HealthTopics:
      - HealthTopic: /pc_processor/multi_object_tracker/tracked_object_set_map_frame_1
        HealthName: TOSTF
        HealthTopicType: TrackedObjectSet
        NomWarnErrRate: 10, 7, 1
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run: 

  DATF:
    Type: Algorithm
    Description: Transform drivable area to map frame
    Trigger:
      - Source: Startup
    Commands:
      - Name: DAMap
        Command: python ${HOME}/projects/fvla-infrapod/calibration_scripts/FY_24_calib_scripts/infrapod_code/publish_DABP_map.py 1
        Type: Algorithm
        LaunchTime: 3.0
    HealthTopics:
      - HealthTopic: /drivable_area_boundary_points_map_frame_1
        HealthName: DATF
        HealthTopicType: PointCloud2
        NomWarnErrRate: 10, 7, 1
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:  

  VATF:
    Type: Algorithm
    Description: Transform visible space ray points to map frame
    Trigger:
      - Source: Startup
    Commands:
      - Name: VisibleSpaceRayPointsMap
        Command: python ${HOME}/projects/fvla-infrapod/calibration_scripts/FY_24_calib_scripts/infrapod_code/publish_VARP_map.py 1
        Type: Algorithm
        LaunchTime: 3.0
    HealthTopics:
      - HealthTopic: /pc_processor/visible_space/visible_space_ray_points_map_frame_1
        HealthName: VSRPTF
        HealthTopicType: VisibleSpacePoints
        NomWarnErrRate: 10, 7, 1
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:  

  GPS:
    Type: Sensor
    Description: F9R
    Trigger:
      - Source: Startup
    HealthTopics:
      - HealthTopic: /dynamic_global_pose
        HealthName: DGP
        HealthTopicType: DynamicPoseWithCovar
        NomWarnErrRate: 5, 2, 1
    Commands:
      - Name: F9R
        Command: python ${HOME}/projects/fvla-infrapod/gps/publish_pose.py
        NodeName: ublox_gps_F9R
        Type: Software
        LaunchTime: 3
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:

  CAM:
    Type: Sensor
    Description: Camera streaming
    Trigger:
      - Source: Startup
    Commands:
      - Name: Start Camera
        Command: bash ${HOME}/projects/fvla-infrapod/start_camera.sh 
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:

  TEL:
    Type: Software
    Description: Telemetry over MQTT
    Trigger:
      - Source: Startup
    Commands:
      - Name: MQTT Telemetry
        Command: bash ${HOME}/projects/fvla-infrapod/start_telemetry.sh 
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:
