Configuration:
  Name: Mike
  mapName: Franklin.set
  printTimeDebug: 0
  useGui: 1
  sendWm: 1
  sendSnapshots: 0
  broker: ncal

Subsystem:
  CAR:
    Type: Sensor
    Description: Vehicle CAN and EyeQ5
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: Startup
    HealthTopics:
      - HealthTopic: /CAN/health
        HealthName: CAR
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /pmu_state
        HealthName: PMU
        HealthTopicType: Int16MultiArray
        NomWarnErrRate: 10, 8, 1
    Commands:
      - Name: CanAriyaSvITSConsumer
        Command: roslaunch nrc_leaf can_communication_modular.launch numChannels:=5 CanAriyaSvITS3Consumer:=true CanAriyaSvITS3ConsumerCh:=0 CanAriyaSvITS4Consumer:=true CanAriyaSvITS4ConsumerCh:=1 CanAriyaSvITS5Consumer:=true CanAriyaSvITS5ConsumerCh:=3  CanAriyaSvWriter:=true CanAriyaSvWriterCh:=2 Eyeq5DevCh0:=true Eyeq5DevCh0Ch:=4 Eyeq5DevWrite:=true Eyeq5DevWriteCh:=4
        Type: Software
        LaunchTime: 5.0
    Diagnostic:
      LED: 0
      Retry: 3
      Timeout: 5
    Depends:
      - Launch:
        Run:

  Pose:
    Type: Sensor
    Description: Ublox F9R gps and ntrip
    Trigger:
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /gps_state/dynamic_global_pose_f9r_20hz
        HealthName: RAW
        HealthTopicType: DynamicPoseWithCovar
        NomWarnErrRate: 100, 80, 60
      - HealthTopic: /dynamic_global_pose
        HealthName: DGP
        HealthTopicType: DynamicPoseWithCovar
        NomWarnErrRate: 100, 80, 60
    Commands:
      - Name: f9r_raw
        Command: roslaunch nrc_hw_svcs f9r_udev_rule.launch
        Type: Software
        LaunchTime: 1.0
      - Name: TF_Sys
        Command: roslaunch nrc_svcs leaf_tf_subsystem.launch sanborn:=true
        Type: Software
        LaunchTime: 1.0
      - Name: f9r_conv
        Command: rosrun nrc_hw_svcs ublox_f9r_conv --name ublox_conv
        Type: Software
        LaunchTime: 1.0
      - Name: MapMatch
        Command: rosrun nrc_wm2_svcs map_match name:=MapMatch_node _useF9r:=true _useLaneMap:=true
        NodeName: MapMatch_node
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      LED: 1
      Retry: 3
      Timeout: 5
    Depends:
      - Launch:
        Run:

  Cubtek:
    Type: Sensor
    Description: Cubtek 4D imaging radars, left and right
    Trigger:
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /Cubtek/health
        HealthName: NOD
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /cubtek_raw_points
        HealthName: CAN
        HealthTopicType: CubtekRadarArray
        NomWarnErrRate: 15, 9, 3
    Commands:
      - Name: Cubtek_eth_raw_left
        Command: sudo $HOME/projects/nrc_ws/devel/lib/nrc_hw_svcs/pcap eno1 45161 #Left cubtek radar
        Type: Software
        LaunchTime: 2.0
      - Name: Cubtek_eth_raw_right
        Command: sudo $HOME/projects/nrc_ws/devel/lib/nrc_hw_svcs/pcap eno1 45162 #Right cubtek radar
        Type: Software
        LaunchTime: 2.0
      - Name: Cubtek_eth_nodes_left
        Command: rosrun nrc_hw_svcs consume_cubtek cubtek_L 45161
        Type: Software
        LaunchTime: 2.0
      - Name: Cubtek_eth_nodes_right
        Command: rosrun nrc_hw_svcs consume_cubtek cubtek_R 45162
        Type: Software
        LaunchTime: 2.0
      - Name: Cubtek_fuse
        Command: rosrun nrc_wm2_svcs cubtek_fuse
        Type: Software
        LaunchTime: 2.0
    Diagnostic:
      LED: 2
      Retry: 3
      Timeout: 5
    Depends:
      - Launch:
        Run:

  InnovusionPCP:
    Type: Algorithm
    Description: Pointcloud_Processing
    Trigger:
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /pc_processor/multi_object_tracker/tracked_object_set
        HealthName: TOS
        HealthTopicType: TrackedObjectSet
        NomWarnErrRate: 10, 7, 3
      - HealthTopic: /drivable_area_boundary_points
        HealthName: DA
        HealthTopicType: PointCloud2
        NomWarnErrRate: 10, 7, 3
    Commands:
      - Name: InnovusionDriver
        Command: rosrun nrc_svcs  runInnovusion.sh
        Type: Software
        LaunchTime: 1.0
      - Name: PCP
        Command: roslaunch nrc_pcp_svcs pc_processor.launch Leaf_Foxtrot:=true do_curb_detection:=false do_curb_points_accumulation:=false include_curb_points_for_drivable_area:=false include_lateral_curb_points_for_drivable_area:=false include_accumulated_curb_points_for_drivable_area:=false srcgs/cluster_height_threshold:=0.3 dynamic_global_pose_topic_name:=/dynamic_global_pose
        Type: Software
        LaunchTime: 3.0
      - Name: Me2Yolo
        Command: roslaunch nrc_perc_svcs mobileye_yolo_converters.launch
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      LED: 4
      Retry: 3
      Timeout: 5
    Depends:
      - Launch: EYEQ5
        Run:

  WM:
    Type: Algorithm
    Description: World Model
    Trigger:
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /object_tracker/health
        HealthName: FUS
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /traffic_light/detection/health
        HealthName: TLR
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 1, 0.5, 0.2
      - HealthTopic: /ailsv_virtual_objects
        HealthName: VRT
        HealthTopicType: TrackedObjectSet
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /master_filter/health
        HealthName: WOS
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: WM
        Command: roslaunch nrc_wm2_svcs leaf_pred.launch
        Type: Software
        LaunchTime: 1.0
    Diagnostic:
      LED: 5
      Retry: 3
      Timeout: 5
    Depends:
      - Launch: LUMPCP
        Run:

  PLAN:
    Type: Algorithm
    Description: AutoGoals
    Trigger:
      - Source: StartRequest
    HealthTopics:
     - HealthTopic: /modia/route_plan/health
        HealthName: ROUTE
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 1, 0.5, 0.2
      - HealthTopic: /autoGoals/health
        HealthName: GOALS
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /prm/risk_field/health
        HealthName: RSKFLD
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /lane_planner_state
        HealthName: TRP
        HealthTopicType: LanePlannerState
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /lane_follower_state
        HealthName: TRC
        HealthTopicType: TrajectoryControllerState
        NomWarnErrRate: 100, 60, 10
    Commands:
      - Name: Route
        Command: roslaunch nrc_dm_svcs modia_all.launch autonomy_level:=ad5 use_modia_decisions:=false
        Type: Software
        LaunchTime: 3.0
      - Name: RouteGoalGenerator
        Command: rosrun nrc_dm_svcs 
      - Name: AutoGoals
        Command: rosrun nrc_wm2_svcs auto_goals2 __name:=AutoGoals_node
        NodeName: AutoGoals_node
        Type: Software
        LaunchTime: 3.0
      - Name: Trajectory Planner
        Command: roslaunch nrc_ralp_svcs leaf_planner.launch use_predictor:=true publish_force_control:=true vehicle_type:=LeafFS
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      LED: 6
      Retry: 3
      Timeout: 5
    Depends:
      - Launch: WM
        Run:

  BAG:
    Type: Algorithm
    Description: Record bagfiles
    Trigger:
      - Source: ARD2
    HealthTopics:
      - HealthTopic: /BagfileHealth
        HealthName: BAG
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /snapshotTrigger/health_status
        HealthName: TRIG
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /SnapshotHealth
        HealthName: SBAG
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: BAG
        Command: roslaunch nrc_av_ui record_separately_mike.launch
        Type: Software
        LaunchTime: 3.0
      #- Name: SNAP
        #Command: roslaunch nrc_av_ui snapshotPipeline.launch
        #Type: Software
        #LaunchTime: 3.0
    Diagnostic:
      LED: 7
      Retry: 0
      Timeout: 5
    Depends:
      - Launch:
        Run:
