Configuration:

Brokers:
  doris:
    MQTT_SERVER: doris.ail-sv.com
    MQTT_PORT: 8883
    MQTT_USER: sam_teleop
    MQTT_PASSWORD: yg#eo5cbAksD82qt
    MQTT_TLS: true
  
  ncal:
    MQTT_SERVER: mqtt-broker-ncal.nrcsv.com
    MQTT_PORT: 8883
    MQTT_USER: sam-teleop
    MQTT_PASSWORD: yg#eo5cbAksD82qt
    MQTT_TLS: true
    
  emqx:
    MQTT_SERVER: avt-mqtt.nrcsv.com
    MQTT_PORT: 30203
    MQTT_USER: av_team_client
    MQTT_PASSWORD: atfRKyUeprZqjv9m8i
    MQTT_TLS: true
  
  quic:
    MQTT_SERVER: 127.0.0.1
    MQTT_PORT: 1883
    MQTT_USER: quic_mqtt
    MQTT_PASSWORD: A9g7bW#NyLQ4PIZr
    MQTT_TLS: false

  local:
    MQTT_SERVER: 127.0.0.1
    MQTT_PORT: 1883
    MQTT_USER: 
    MQTT_PASSWORD: 
    MQTT_TLS: false
  
  devel:
    MQTT_SERVER: kitt
    MQTT_PORT: 8883
    MQTT_USER: sam_teleop
    MQTT_PASSWORD: yg#eo5cbAksD82qt
    MQTT_TLS: true

  ccm:
    MQTT_SERVER: ccm-mqtt.nrcsv.com
    MQTT_PORT: 30203
    MQTT_USER: ccm_team
    MQTT_PASSWORD: wiA97kgB0TyvXYhb
    MQTT_TLS: true

  ym0_aws:
    MQTT_SERVER: asq16ad9vujas-ats.iot.ap-northeast-1.amazonaws.com
    MQTT_PORT: 8883
    CA_PATH: /home/nissan/Documents/viju/AmazonRootCA1.pem
    CERT_PATH: /home/nissan/Documents/viju/certificate.pem.crt
    KEY_PATH: /home/nissan/Documents/viju/private.pem.key
    MQTT_TLS: true
    IOT_CORE: true