Configuration:
  Name: quebecBlue
  mapName: Franklin.set
  printTimeDebug: 0
  useGui: 1
  sendWm: 1
  sendSnapshots: 1
  broker: ccm

Subsystem:
  CCM-CAR:
    Type: Sensor
    Description: Vehicle Network
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: Startup
    HealthTopics:
      - HealthTopic: /CAN_V_reader
        HealthName: CAN
        HealthTopicType: CANVReader
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /ME4_ObjData
        HealthName: ME4
        HealthTopicType: Mobileye4ObjectArray
        NomWarnErrRate: 10, 6, 3 
    Commands:
      - Name: CanReader
        Command: roslaunch nrc_leaf can_communication_modular.launch numChannels:=4 CanAriyaSvITS3Consumer:=true CanAriyaSvITS3ConsumerCh:=0 CanAriyaSvITS4Consumer:=true CanAriyaSvITS4ConsumerCh:=1 CanAriyaSvITS5Consumer:=true CanAriyaSvITS5ConsumerCh:=2 CanAriyaSvITS1Consumer:=true CanAriyaSvITS1ConsumerCh:=3
        Type: Software
        LaunchTime: 5.0
      - Name: EthRawReader
        Command: python ~/projects/nrc_ws/src/nrc_leaf/scripts/eth_raw.py
        Type: Software
        LaunchTime: 5.0
      - Name: EthReader
        Command: rosrun nrc_leaf consume_eth_can
        Type: Software
        LaunchTime: 5.0
    Diagnostic:
      LED: 0
      Retry: 3
      Timeout: 5
    Depends:
      - Launch:
        Run:

  Pose:
    Type: Sensor
    Description: Raw GPS
    Trigger:
      - Source: Startup
    HealthTopics:
      - HealthTopic: /gps_state
        HealthName: GPS
        HealthTopicType: GpsState
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: GPS_Raw
        Command: roslaunch nrc_hw_svcs swiftnav_gps.launch
        Type: Software
        LaunchTime: 1.0
      - Name: SwiftNavConv
        Command: rosrun nrc_hw_svcs swiftnav_conv.py --node_name swiftnav_conv --map_shift_cfg=`rospack find nrc_hw_svcs`/scripts/cfg/demo2021_mapShift.json
        NodeName: swiftnav_conv
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      LED: 1
      Retry: 3
      Timeout: 5
    Depends:
      - Launch:
        Run:

  CCM:
    Type: Algorithm
    Description: CCM
    Trigger:
      - Source: StartRequest
    HealthTopics: 
      - HealthTopic: /ccm_acc_control_h
        HealthName: CCM
        HealthTopicType: String
        NomWarnErrRate: 10, 6, 3 
      - HealthTopic: /ProPILOT_inputs
        HealthName: PPI
        HealthTopicType: ProPILOTInput
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /ccm_speed_plan
        HealthName: CSP
        HealthTopicType: String
        NomWarnErrRate: 0.1, 0.01, 0.01
    Commands:
      - Name: ACC Trigger
        Command: roslaunch ccm_acc_trigger ccm_acc_trigger.launch
        NodeName: ccm_acc_trigger_node
        Type: Software
        LaunchTime: 3.0
      - Name: CCM ACC CAR
        Command: roslaunch ccm_cav_car ccm_cav_rl_acc_blueQuebec.launch veh_id:=ccm_cav-blueQuebec
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      LED: 6
      Retry: 3
      Timeout: 5
    Depends:
      - Launch: 
        Run:

  LTSWM:
    Type: Algorithm
    Description: LTSWM
    Trigger:
      - Source: StartRequest
    HealthTopics: 
      - HealthTopic: /probe_vehicle_publisher_h
        HealthName: PVP
        HealthTopicType: String
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: LTSWM pub
        Command: roslaunch ltswm_cv ltswm_cv.launch veh_id:=cav-blueQuebec
        NodeName: ltswm_cv_mqtt_pub:blueQuebec
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      LED: 6
      Retry: 3
      Timeout: 5
    Depends:
      - Launch: 
        Run:

  BAG:
    Type: Algorithm
    Description: Record bagfiles
    Trigger:
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /BagfileHealth
        HealthName: BAG
        HealthTopicType: DiagnosticArray
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: BAG
        Command: roslaunch nrc_av_ui record_ccm_car.launch
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      LED: 7
      Retry: 0
      Timeout: 5
    Depends:
      - Launch:
          Run:


