Configuration:
  Name: NRC_Leaf_Hotel
  agentType: AV1
  mapName: Franklin.set
  printTimeDebug: 0
  useGui: 0
  sendWm: 0
  sendSnapshots: 0
  broker: doris

ROSParams:
  vehicleFeeder/sourceMode: MODE_DYNAMIC_POSE
  vehicleFeeder/dynamicPoseTopicName: /dynamic_global_pose
  dynamicPoseTopic_f9r: /dynamic_global_pose_F9R
  gps_stateTopic_f9r: /gps_state
  devname: /dev/gps/ublox/F9R
  f9r_devname: /dev/gps/ublox/F9R
  f9rRTCM_devname: /dev/gps/ublox/F9R_RTCM

Subsystem:
  CAR:
    Type: Sensor
    Description: Vehicle CAN
    Trigger: Startup or StartRequest
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 6, 3
    Commands:
      - Name: CanXH0
        Command: roslaunch nrc_leaf can_communication_modular.launch numChannels:=4 CanAdasWriterXH0:=true CanAdasWriterXH0Ch:=2 CanVConsumer:=true CanVConsumerCh:=0
        Type: Software
        LaunchTime: 5.0
    Diagnostic:
      Retry: 3
      Timeout: 5
    Depends:
      - Launch:
        Run:

  Pose:
    Type: Sensor
    Description: Raw GPS
    Trigger:
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /dynamic_global_pose_F9R
        HealthName: F9R
        HealthTopicType: DynamicPoseWithCovar
        NomWarnErrRate: 20, 5, 2
      - HealthTopic: /gps_state
        HealthName: GPS
        HealthTopicType: DynamicPoseWithCovar
        NomWarnErrRate: 20, 5, 2
      - HealthTopic: /dynamic_global_pose
        HealthName: PE
        HealthTopicType: DynamicPoseWithCovar
        NomWarnErrRate: 100, 80, 60
    Commands:
      - Name: F9R
        Command: roslaunch nrc_hw_svcs f9r.launch
        Type: Software
        LaunchTime: 1.0
      - Name: TF_Sys
        Command: roslaunch nrc_svcs leaf_tf_subsystem.launch sanborn:=true
        Type: Software
        LaunchTime: 1.0
        - Name: Pose Estimator
        Command: roslaunch pose_estimator pose_estimator.launch
        Type: Software
        LaunchTime: 1.0
    Diagnostic:
      Retry: 3
      Timeout: 5
    Depends:
      - Launch:
        Run:

  MQTT:
    Type: Software
    Description: ROS traffic over MQTT
    Trigger:
      - Source: StartRequest
    Commands:
      - Name: ROS-MQTT-Bridge
        Command: roslaunch $HOME/projects/fvla-vehiclepod/nrc_ws/src/mqtt-client-config/launch/standalone_local.launch params_file:="$HOME/projects/fvla-vehiclepod/nrc_ws/src/mqtt-client-config/fvla-dev/test2/params_local_ego_fvla.yaml"
        NodeName: mqtt_client_local
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      Retry: 3
      Timeout: 3
      Depends:
      - Launch:
        Run:
  
  FLWR:
    Type: Algorithm
    Description: Trajectory Follower
    Trigger:
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /vehicle_trajectory_control
        HealthName: TRJ
        HealthTopicType: VehicleTrajectoryControl
        NomWarnErrRate: 10, 6, 3
      - HealthTopic: /control_inputs
        HealthName: CTRL
        HealthTopicType: ForceSteeringControl
        NomWarnErrRate: 100, 80, 60
      - HealthTopic: /lane_follower_state
        HealthName: TRC
        HealthTopicType: TrajectoryControllerState
        NomWarnErrRate: 100, 60, 10
    Commands:
      - Name: Follower
        Command: roslaunch nrc_ralp_svcs leaf_follower.launch vehicle_type:=Leaf_Hotel
        NodeName: Trajectory Follower
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      LED: 6
      Retry: 3
      Timeout: 5
    Depends:
      - Launch: MQTT
        Run:

  HM:
    Type: Algorithm
    Description: Health Monitor
    Trigger:
      - Source: StartRequest
    Commands:
      - Name: Start Health Monitor
        Command: roslaunch health-monitor vehicle_health.launch config_file:=$HOME/projects/fvla-vehiclepod/src/configs/health-monitor/Vehicle_HealthCheck.yaml
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:

  CAM:
    Type: Sensor
    Description: Camera streaming
    Trigger:
      - Source: StartRequest
    Commands:
      - Name: Start Camera
        Command: bash ${HOME}/projects/fvla-vehiclepod/scripts/3_start_camera.sh 
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:

  TEL:
    Type: Software
    Description: Telemetry over MQTT
    Trigger:
      - Source: StartRequest
    Commands:
      - Name: Telemetry
        Command: bash ${HOME}/projects/fvla-vehiclepod/scripts/3_start_telemetry.sh 
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:
  
  BAG:
    Type: Software
    Description: Automated recorder
    Trigger:
      - Source: StartRequest
    Commands:
      - Name: Start Recorder
        Command: bash ${HOME}/projects/fvla-vehiclepod/scripts/4_start_recording.sh
        Type: Software
        LaunchTime: 3.0
    Diagnostic:
      Retry: 3
      Timeout: 3
    Depends:
      - Launch:
        Run:
