Configuration:
  Name: sim
  agentType: AV4
  mapName: Franklin.set
  printTimeDebug: 0
  useGui: 1
  sendWm: 1
  imgTopic: /tower_cam_front/image_stamped/compressed
  wmTopic: /pc_processor/multi_object_tracker/tracked_object_set
  sendSnapshots: 0
  broker: emqx
  
      <arg name="vehicle" value="ze1-01"/>
    <arg name="location" value="mm"/>

    <!-- Machines to use -->
    <arg name="ctrl_machine" value="master"/>
    <arg name="gps_machine" value="master"/>
    <arg name="ibeo_machine" value="master" />
    <arg name="watec_front_machine" value="airtop01" />
    <arg name="watec_side_machine" value="airtop01" />
    <arg name="watec_rear_machine" value="airtop01" />
    <arg name="tieriv_machine" value="jetson02" />
    <arg name="avm_machine" value="airtop03" />
    <arg name="ndt_machine" value="airtop02" />
    <arg name="luminar_machine" value="airtop02" />
    <arg name="velodyne_machine" value="airtop02" />
    <arg name="hesai_machine" value="airtop02" />
    <arg name="bosch_com_machine" value="master" />
    <arg name="traffic_light_machine" value="airtop05" />
    <arg name="traffic_light_ped_machine" value="airtop05" />
    <arg name="meye3_machine" value="airtop01" />
    <arg name="pointcloud_processing_machine" value="airtop02" />
    <arg name="bevfusion_machine" value="zbox01" />
    <arg name="image_processing_machine" value="airtop01" />
    <arg name="vehicle_light_detection_machine" value="airtop04" />
    <arg name="sensor_fusion_machine" value="airtop02" />
    <arg name="local_model_machine" value="master" />
    <arg name="route_planner_machine" value="master" />
    <arg name="behavior_exec_machine" value="master" />
    <arg name="path_planning_machine" value="airtop03" />
    <arg name="mfield_machine" value="airtop01" />
    <arg name="teleop_machine" value="nuvo"/>

    <!-- GPS -->
    <arg name="use_trimble" value="false"/>
    <arg name="use_garmin" value="false"/>
    <arg name="use_oxts" value="true"/>

    <!-- Sensors -->
    <arg name="use_ibeo" value="true"/>
    <arg name="use_watec" value="false"/>
    <arg name="use_tieriv" value="true"/>
    <arg name="use_avm" value="true"/>
    <arg name="use_meye3" value="true"/>
    <arg name="use_meye3_trw" value="false"/>
    <arg name="use_luminar" value="true"/>
    <arg name="use_velodyne" value="false"/>
    <arg name="use_hesai" value="true"/>
    <arg name="use_bosch_radar" value="true"/>
    <arg name="use_traffic_lights" value="true"/>
    <arg name="ibeoIpAddress" value="192.168.1.100"/>

    <!-- Decision Making -->
    <arg name="use_decision_for_private_area" value="true"/>
  
    <!-- MABX Communication -->
  <node pkg="nrc_svcs" type="nrc_mab_com" name="mab_com" machine="$(arg ctrl_machine)"/>
  <node pkg="nrc_svcs" type="nrc_mfield" name="nrc_mfield" machine="$(arg mfield_machine)" respawn="true">
    <param name="mfield_lpf_value" value="0.5" type="double"/>
  </node>
  
  

Subsystem:
  Car:
    Type: Sensor
    Description: command to start simulator
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: CAN Communication
        Command: roslaunch nrc_leaf can_communication_ym0.launch ctrl_machine:=master meye3_machine:=airtop01 use_meye3:=true
        NodeName: CanComNode
        Type: Software
        LaunchTime: 1
      - Name: Mabx Communication
        Command: rosrun nrc_svcs nrc_mab_com __name:=mab_com __ctrl_machine:=master
        NodeName: MabComNode
        Type: Software
        LaunchTime: 1
      - Name: M-Field Node
        Command: rosrun nrc_svcs nrc_mfield __name:=nrc_mfield __machine:=airtop01 __mfield_lpf_value:=0.5
        NodeName: MabComNode
        Type: Software
        LaunchTime: 1
      - Name: Leaf TF
        Command: roslaunch nrc_svcs leaf_tf_subsystem.launch
        NodeName: MabComNode
        Type: Software
        LaunchTime: 1
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:
        
  Teleop:
    Type: Sensor
    Description: command to start simulator
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: CAN Communication
        Command: roslaunch nrc_leaf can_communication_ym0.launch ctrl_machine:=master meye3_machine:=airtop01 use_meye3:=true
        NodeName: CanComNode
        Type: Software
        LaunchTime: 1
      - Name: Mabx Communication
        Command: rosrun nrc_svcs nrc_mab_com __name:=mab_com __ctrl_machine:=master
        NodeName: MabComNode
        Type: Software
        LaunchTime: 1
      - Name: M-Field Node
        Command: rosrun nrc_svcs nrc_mfield __name:=nrc_mfield __machine:=airtop01 __mfield_lpf_value:=0.5
        NodeName: MabComNode
        Type: Software
        LaunchTime: 1
      - Name: Leaf TF
        Command: roslaunch nrc_svcs leaf_tf_subsystem.launch
        NodeName: MabComNode
        Type: Software
        LaunchTime: 1
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:
    
  
