Configuration:
  Name: sim
  agentType: AV4
  mapName: Franklin.set
  printTimeDebug: 0
  useGui: 1
  sendWm: 1
  imgTopic: /tower_cam_front/image_stamped/compressed
  wmTopic: /pc_processor/multi_object_tracker/tracked_object_set
  sendSnapshots: 0
  broker: ym0_aws
  
Subsystem:

  NUVO:
    Type: NUVO
    Description: command to start NUVO PC
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: NUVO_Startup
        Command: roslaunch /home/nissan/Documents/remote_start_launch/remote_launch_FY23_OTA.launch vehicle:=ze1-01 machine:=nuvo
        NodeName: NUVOStartmNode
        Type: Software
        LaunchTime: 1
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:


  Car:
    Type: Basic
    Description: Vehicle basic function startup
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: Basic
        Command: roslaunch /home/nissan/Documents/remote_start_launch/basic_OTA.launch
        NodeName: MabComNode
        Type: Software
        LaunchTime: 1   
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:
        
  Teleop:
    Type: Teleop
    Description: command to start simulator
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: TeleOp IF
        Command: roslaunch /home/nissan/Documents/remote_start_launch/Teleop_OTA.launch
        NodeName: TeleOp
        Type: Software
        LaunchTime: 1
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:
    
  GPS:
    Type: GPS
    Description: GPS
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: GPS_Startup
        Command: roslaunch /home/nissan/Documents/remote_start_launch/GPS_OTA.launch gps_machine:=master ndt_machine:=airtop02 location:=mm use_trimble:=false use_garmin:=false use_oxts:=true
        NodeName: GPS
        Type: Software
        LaunchTime: 1       
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:


  Perc:
    Type: Sensors
    Description: sensors
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: sensors_Startup
        Command: roslaunch /home/nissan/Documents/remote_start_launch/sensors_OTA.launch vehicle:=ze1-01 use_ibeo:=true use_watec:=false use_tieriv:=true use_avm:=true use_luminar:=true use_velodyne:=false use_hesai:=true use_traffic_lights:=true ibeo_machine:=master ibeoIpAddress:=192.168.1.100 watec_front_machine:=airtop01 watec_side_machine:=airtop01 watec_rear_machine:=airtop01 tieriv_machine:=jetson02 avm_machine:=airtop03 luminar_machine:=airtop02 velodyne_machine:=airtop02 hesai_machine:=airtop02 traffic_light_machine:=airtop05
        NodeName: GPS
        Type: Software
        LaunchTime: 1
      - Name: ym0_perc_Startup
        Command: roslaunch /home/nissan/Documents/remote_start_launch/perception_ym0_OTA.launch vehicle:=ze1-01 location:=mm pointcloud_processing_machine:=airtop02 bevfusion_machine:=zbox01 image_processing_machine:=airtop01 vehicle_light_detection_machine:=airtop04 sensor_fusion_machine:=airtop02 traffic_light_machine:=airtop05 traffic_light_ped_machine:=airtop05
        NodeName: GPS
        Type: Software
        LaunchTime: 1       
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:

  Bosch:
    Type: bosch
    Description: bosch
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: bosch_Startup
        Command: roslaunch /home/nissan/Documents/remote_start_launch/bosch_OTA.launch   nrc_bosch_com:=master
        NodeName: bosch
        Type: Software
        LaunchTime: 1      
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:

  Localization:
    Type: Localization
    Description: Localization
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: localization_Startup
        Command: roslaunch /home/nissan/Documents/remote_start_launch/localization_OTA.launch
        NodeName: localization
        Type: Software
        LaunchTime: 1   
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:

  Local_Model:
    Type: Local_model
    Description: local_model&Data_conversion_startup&Image_reduce_startup
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: localization_Startup
        Command: roslaunch /home/nissan/Documents/remote_start_launch/local_model_OTA.launch
        NodeName: localization
        Type: Software
        LaunchTime: 1   
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:

  Route_planner:
    Type: route_planner
    Description: route_planner
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: routeplanner_Startup
        Command: roslaunch /home/nissan/Documents/remote_start_launch/route_planner_OTA.launch use_decision_for_private_area:=true use_ym0_crossing_vehicle_decision:=true use_decision_for_straight_crosswalk:=true use_traffic_light_decisions:=true
        NodeName: routeplanner
        Type: Software
        LaunchTime: 1   
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:
  

  WM:
    Type: world_model
    Description: world_model
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: world_model
        Command: roslaunch /home/nissan/Documents/remote_start_launch/worldmodel_OTA.launch 
        NodeName: world_model
        Type: Software
        LaunchTime: 1
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run:

  DM:
    Type: Decision_making
    Description: Decision_making
    Trigger: Startup, StartRequest, ARDX, or PMUX
      - Source: StartRequest
    HealthTopics:
      - HealthTopic: /CtrlStateFLG_10hz
        HealthName: CAR
        HealthTopicType: CtrlStateFLG
        NomWarnErrRate: 10, 7, 5
    Commands:
      - Name: DecisionMaking_Startup
        Command: roslaunch /home/nissan/Documents/remote_start_launch/DM_OTA.launch
        NodeName: Data_conversion
        Type: Software
        LaunchTime: 1
    Diagnostic:
      Retry: 3
      Timeout: 220
    Depends:
      - Launch:
        Run: