const ipcMsg = {
  R2M: {
    REGISTER_INFO: 'REGISTER_INFO',
    GET_STORAGE: 'GET_STORAGE',
    SET_STORAGE: 'SET_STORAGE',
    UPDATE_VEHICLE: 'UPDATE_VEHICLE'
  },
  M2R: {
    REGISTER_INFO_REPLY: 'REGISTER_INFO_REPLY',
    CONNECTION_INFO_REPLY: 'CONNECTION_INFO_REPLY',
    VEHICLE_STATUS: 'VEHICLE_STATUS',
    VEHICLE_CONNECTION_STATUS: 'VEHICLE_CONNECTION_STATUS',
    NAVIGATE: 'NAVIGATE',
    UPDATE_VEHICLE_REPLY: 'UPDATE_VEHICLE_REPLY'
  },
  RMR: {
    VEHICLE_INFO: 'VEHICLE_INFO',
    CONNECTION_INFO: 'CONNECTION_INFO',
    VEHICLE_STATUS_REQUEST: 'VEHICLE_STATUS',
    VEHICLE_CONNECTION_STATUS_REQUEST: 'VEHICLE_CONNECTION_STATUS'
  },
  storageKeys: {
    EXAMPLE_KEY: 'EXAMPLE_KEY'
  }
};

export default ipcMsg;
